import type { RepoAnalysis } from "./setupScriptGenerator";

export function generateSetupInstructions(
  repoName: string,
  analysis: RepoAnalysis,
): string {
  const lines: string[] = [
    `# Setup Guide for ${repoName}`,
    "",
    "> Auto-generated by Repo Radar AI Setup Assistant",
    "",
    "## Prerequisites",
    "",
  ];

  // Prerequisites
  if (analysis.hasPackageJson) {
    lines.push(
      `- **Node.js** ${analysis.nodeVersion ? `(${analysis.nodeVersion})` : "(v18+ recommended)"} — [Download](https://nodejs.org)`,
    );
    if (analysis.packageManager === "yarn")
      lines.push("- **Yarn** — `npm install -g yarn`");
    if (analysis.packageManager === "pnpm")
      lines.push("- **pnpm** — `npm install -g pnpm`");
    if (analysis.packageManager === "bun")
      lines.push("- **Bun** — [Download](https://bun.sh)");
  }
  if (analysis.hasRequirements) {
    lines.push("- **Python 3.8+** — [Download](https://python.org)");
    lines.push("- **pip** (usually included with Python)");
  }
  if (analysis.hasCargo) {
    lines.push("- **Rust** — [Install via rustup](https://rustup.rs)");
  }
  if (analysis.hasGoMod) {
    lines.push("- **Go 1.19+** — [Download](https://go.dev)");
  }
  if (analysis.hasGemfile) {
    lines.push("- **Ruby 3.0+** — [Download](https://ruby-lang.org)");
    lines.push("- **Bundler** — `gem install bundler`");
  }
  if (analysis.hasDocker || analysis.hasDockerCompose) {
    lines.push("- **Docker** — [Download](https://docker.com)");
    if (analysis.hasDockerCompose)
      lines.push("- **Docker Compose** — included with Docker Desktop");
  }

  lines.push("");
  lines.push("## Installation Steps");
  lines.push("");

  let step = 1;

  lines.push(`### Step ${step++}: Clone the Repository`);
  lines.push("");
  lines.push("```bash");
  lines.push(`git clone https://github.com/${repoName}.git`);
  lines.push(`cd ${repoName.split("/")[1] || repoName}`);
  lines.push("```");
  lines.push("");

  if (analysis.envVars.length > 0) {
    lines.push(`### Step ${step++}: Configure Environment Variables`);
    lines.push("");
    lines.push("Copy the example environment file and fill in your values:");
    lines.push("");
    lines.push("```bash");
    lines.push("cp .env.example .env");
    lines.push("```");
    lines.push("");
    lines.push("Required environment variables:");
    lines.push("");
    for (const v of analysis.envVars) {
      lines.push(`- \`${v}\``);
    }
    lines.push("");
  }

  if (analysis.hasPackageJson) {
    const pm = analysis.packageManager || "npm";
    lines.push(`### Step ${step++}: Install Node.js Dependencies`);
    lines.push("");
    lines.push("```bash");
    lines.push(`${pm} install`);
    lines.push("```");
    lines.push("");

    if (analysis.scripts.build) {
      lines.push(`### Step ${step++}: Build the Project`);
      lines.push("");
      lines.push("```bash");
      lines.push(`${pm} run build`);
      lines.push("```");
      lines.push("");
    }

    lines.push(`### Step ${step++}: Start the Application`);
    lines.push("");
    lines.push("```bash");
    if (analysis.scripts.dev) {
      lines.push(`${pm} run dev`);
    } else if (analysis.scripts.start) {
      lines.push(`${pm} start`);
    } else {
      lines.push(`${pm} start  # or check package.json scripts`);
    }
    lines.push("```");
    lines.push("");
  }

  if (analysis.hasRequirements) {
    lines.push(`### Step ${step++}: Set Up Python Environment`);
    lines.push("");
    lines.push("```bash");
    lines.push("python3 -m venv venv");
    lines.push("source venv/bin/activate  # Windows: venv\\Scripts\\activate");
    lines.push("pip install -r requirements.txt");
    lines.push("```");
    lines.push("");
    lines.push(`### Step ${step++}: Run the Application`);
    lines.push("");
    lines.push("```bash");
    lines.push(
      "python main.py  # or python app.py — check README for exact command",
    );
    lines.push("```");
    lines.push("");
  }

  if (analysis.hasCargo) {
    lines.push(`### Step ${step++}: Build and Run (Rust)`);
    lines.push("");
    lines.push("```bash");
    lines.push("cargo build --release");
    lines.push("cargo run");
    lines.push("```");
    lines.push("");
  }

  if (analysis.hasGoMod) {
    lines.push(`### Step ${step++}: Build and Run (Go)`);
    lines.push("");
    lines.push("```bash");
    lines.push("go mod download");
    lines.push("go run .");
    lines.push("```");
    lines.push("");
  }

  if (analysis.hasDockerCompose) {
    lines.push("## Alternative: Docker Compose");
    lines.push("");
    lines.push("```bash");
    lines.push("docker-compose up --build");
    lines.push("```");
    lines.push("");
  } else if (analysis.hasDocker) {
    lines.push("## Alternative: Docker");
    lines.push("");
    lines.push("```bash");
    lines.push(`docker build -t ${repoName.split("/")[1] || "app"} .`);
    lines.push(`docker run -p 3000:3000 ${repoName.split("/")[1] || "app"}`);
    lines.push("```");
    lines.push("");
  }

  lines.push("## Troubleshooting");
  lines.push("");
  lines.push("- Check the project README for additional setup instructions");
  lines.push("- Ensure all prerequisites are installed and up to date");
  lines.push("- Check open issues on GitHub for known setup problems");
  lines.push(
    "- Make sure all required environment variables are set correctly",
  );

  return lines.join("\n");
}
